# Use postgres/example user/password credentials
version: '3.8'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 4000:4000
